schema:
  # - ${import.meta.env.VITE_API_ENDPOINT}
  # - "https://shineapi1996.top/api/graphql"
  - https://api.bachgiaphat.vn/apidev/graphql
documents:
  - "./src/graphql/**/*.graphql"
generates:
  ./src/graphql/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
